<?xml version="1.0" encoding="utf-8"?><Database Name="shopgiay" Class="dbStoregiayDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=.\SQLEXPRESS;Initial Catalog=shopgiay;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="shopgiayConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Chitietdonhang" Member="Chitietdonhangs">
    <Type Name="Chitietdonhang">
      <Column Name="idDonhang" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="idSanpham" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Soluong" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="dongia" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Association Name="Donhang_Chitietdonhang" Member="Donhang" ThisKey="idDonhang" OtherKey="idDonhang" Type="Donhang" IsForeignKey="true" />
      <Association Name="Sanpham_Chitietdonhang" Member="Sanpham" ThisKey="idSanpham" OtherKey="idSanpham" Type="Sanpham" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Donhang" Member="Donhangs">
    <Type Name="Donhang">
      <Column Name="idDonhang" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="idKhachhang" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ngayDathang" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ngayGiaohang" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Tinhtranggiaohang" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="Dathanhtoan" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Association Name="Donhang_Chitietdonhang" Member="Chitietdonhangs" ThisKey="idDonhang" OtherKey="idDonhang" Type="Chitietdonhang" />
      <Association Name="Khachhang_Donhang" Member="Khachhang" ThisKey="idKhachhang" OtherKey="idKhachhang" Type="Khachhang" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Khachhang" Member="Khachhangs">
    <Type Name="Khachhang">
      <Column Name="idKhachhang" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="tenKhachhang" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="sdtKhachhang" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="diachiKhachhang" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="ngaysinhKhachhang" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="taikhoanKhachhang" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="matkhauKhachhang" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="emailKhachhang" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Association Name="Khachhang_Donhang" Member="Donhangs" ThisKey="idKhachhang" OtherKey="idKhachhang" Type="Donhang" />
    </Type>
  </Table>
  <Table Name="dbo.Loaisanpham" Member="Loaisanphams">
    <Type Name="Loaisanpham">
      <Column Name="idLoaisanpham" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="tenLoaisanpham" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Association Name="Loaisanpham_Sanpham" Member="Sanphams" ThisKey="idLoaisanpham" OtherKey="idLoaisanpham" Type="Sanpham" />
    </Type>
  </Table>
  <Table Name="dbo.Nhanhieu" Member="Nhanhieus">
    <Type Name="Nhanhieu">
      <Column Name="idNhanhieu" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="tenNhanhieu" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Association Name="Nhanhieu_Sanpham" Member="Sanphams" ThisKey="idNhanhieu" OtherKey="idNhanhieu" Type="Sanpham" />
    </Type>
  </Table>
  <Table Name="dbo.Sanpham" Member="Sanphams">
    <Type Name="Sanpham">
      <Column Name="idSanpham" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="tenSanpham" Type="System.String" DbType="NVarChar(500) NOT NULL" CanBeNull="false" />
      <Column Name="motaSanpham" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="idNhanhieu" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="idLoaisanpham" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="hinhSanpham" Type="System.String" DbType="VarChar(500)" CanBeNull="true" />
      <Column Name="giabanSanpham" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="Soluongton" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ngaycapnhat" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="Sanpham_Chitietdonhang" Member="Chitietdonhangs" ThisKey="idSanpham" OtherKey="idSanpham" Type="Chitietdonhang" />
      <Association Name="Loaisanpham_Sanpham" Member="Loaisanpham" ThisKey="idLoaisanpham" OtherKey="idLoaisanpham" Type="Loaisanpham" IsForeignKey="true" />
      <Association Name="Nhanhieu_Sanpham" Member="Nhanhieu" ThisKey="idNhanhieu" OtherKey="idNhanhieu" Type="Nhanhieu" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Admin" Member="Admins">
    <Type Name="Admin">
      <Column Name="UserAdmin" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="PasswordAdmin" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Hoten" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
</Database>