#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace store_giay.Models
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="shopgiay")]
	public partial class dbStoregiayDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertChitietdonhang(Chitietdonhang instance);
    partial void UpdateChitietdonhang(Chitietdonhang instance);
    partial void DeleteChitietdonhang(Chitietdonhang instance);
    partial void InsertDonhang(Donhang instance);
    partial void UpdateDonhang(Donhang instance);
    partial void DeleteDonhang(Donhang instance);
    partial void InsertKhachhang(Khachhang instance);
    partial void UpdateKhachhang(Khachhang instance);
    partial void DeleteKhachhang(Khachhang instance);
    partial void InsertLoaisanpham(Loaisanpham instance);
    partial void UpdateLoaisanpham(Loaisanpham instance);
    partial void DeleteLoaisanpham(Loaisanpham instance);
    partial void InsertNhanhieu(Nhanhieu instance);
    partial void UpdateNhanhieu(Nhanhieu instance);
    partial void DeleteNhanhieu(Nhanhieu instance);
    partial void InsertSanpham(Sanpham instance);
    partial void UpdateSanpham(Sanpham instance);
    partial void DeleteSanpham(Sanpham instance);
    partial void InsertAdmin(Admin instance);
    partial void UpdateAdmin(Admin instance);
    partial void DeleteAdmin(Admin instance);
    #endregion
		
		public dbStoregiayDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["shopgiayConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public dbStoregiayDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public dbStoregiayDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public dbStoregiayDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public dbStoregiayDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Chitietdonhang> Chitietdonhangs
		{
			get
			{
				return this.GetTable<Chitietdonhang>();
			}
		}
		
		public System.Data.Linq.Table<Donhang> Donhangs
		{
			get
			{
				return this.GetTable<Donhang>();
			}
		}
		
		public System.Data.Linq.Table<Khachhang> Khachhangs
		{
			get
			{
				return this.GetTable<Khachhang>();
			}
		}
		
		public System.Data.Linq.Table<Loaisanpham> Loaisanphams
		{
			get
			{
				return this.GetTable<Loaisanpham>();
			}
		}
		
		public System.Data.Linq.Table<Nhanhieu> Nhanhieus
		{
			get
			{
				return this.GetTable<Nhanhieu>();
			}
		}
		
		public System.Data.Linq.Table<Sanpham> Sanphams
		{
			get
			{
				return this.GetTable<Sanpham>();
			}
		}
		
		public System.Data.Linq.Table<Admin> Admins
		{
			get
			{
				return this.GetTable<Admin>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Chitietdonhang")]
	public partial class Chitietdonhang : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _idDonhang;
		
		private int _idSanpham;
		
		private System.Nullable<int> _Soluong;
		
		private System.Nullable<decimal> _dongia;
		
		private EntityRef<Donhang> _Donhang;
		
		private EntityRef<Sanpham> _Sanpham;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidDonhangChanging(int value);
    partial void OnidDonhangChanged();
    partial void OnidSanphamChanging(int value);
    partial void OnidSanphamChanged();
    partial void OnSoluongChanging(System.Nullable<int> value);
    partial void OnSoluongChanged();
    partial void OndongiaChanging(System.Nullable<decimal> value);
    partial void OndongiaChanged();
    #endregion
		
		public Chitietdonhang()
		{
			this._Donhang = default(EntityRef<Donhang>);
			this._Sanpham = default(EntityRef<Sanpham>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idDonhang", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int idDonhang
		{
			get
			{
				return this._idDonhang;
			}
			set
			{
				if ((this._idDonhang != value))
				{
					if (this._Donhang.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnidDonhangChanging(value);
					this.SendPropertyChanging();
					this._idDonhang = value;
					this.SendPropertyChanged("idDonhang");
					this.OnidDonhangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idSanpham", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int idSanpham
		{
			get
			{
				return this._idSanpham;
			}
			set
			{
				if ((this._idSanpham != value))
				{
					if (this._Sanpham.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnidSanphamChanging(value);
					this.SendPropertyChanging();
					this._idSanpham = value;
					this.SendPropertyChanged("idSanpham");
					this.OnidSanphamChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Soluong", DbType="Int")]
		public System.Nullable<int> Soluong
		{
			get
			{
				return this._Soluong;
			}
			set
			{
				if ((this._Soluong != value))
				{
					this.OnSoluongChanging(value);
					this.SendPropertyChanging();
					this._Soluong = value;
					this.SendPropertyChanged("Soluong");
					this.OnSoluongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dongia", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> dongia
		{
			get
			{
				return this._dongia;
			}
			set
			{
				if ((this._dongia != value))
				{
					this.OndongiaChanging(value);
					this.SendPropertyChanging();
					this._dongia = value;
					this.SendPropertyChanged("dongia");
					this.OndongiaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Donhang_Chitietdonhang", Storage="_Donhang", ThisKey="idDonhang", OtherKey="idDonhang", IsForeignKey=true)]
		public Donhang Donhang
		{
			get
			{
				return this._Donhang.Entity;
			}
			set
			{
				Donhang previousValue = this._Donhang.Entity;
				if (((previousValue != value) 
							|| (this._Donhang.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Donhang.Entity = null;
						previousValue.Chitietdonhangs.Remove(this);
					}
					this._Donhang.Entity = value;
					if ((value != null))
					{
						value.Chitietdonhangs.Add(this);
						this._idDonhang = value.idDonhang;
					}
					else
					{
						this._idDonhang = default(int);
					}
					this.SendPropertyChanged("Donhang");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Sanpham_Chitietdonhang", Storage="_Sanpham", ThisKey="idSanpham", OtherKey="idSanpham", IsForeignKey=true)]
		public Sanpham Sanpham
		{
			get
			{
				return this._Sanpham.Entity;
			}
			set
			{
				Sanpham previousValue = this._Sanpham.Entity;
				if (((previousValue != value) 
							|| (this._Sanpham.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Sanpham.Entity = null;
						previousValue.Chitietdonhangs.Remove(this);
					}
					this._Sanpham.Entity = value;
					if ((value != null))
					{
						value.Chitietdonhangs.Add(this);
						this._idSanpham = value.idSanpham;
					}
					else
					{
						this._idSanpham = default(int);
					}
					this.SendPropertyChanged("Sanpham");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Donhang")]
	public partial class Donhang : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _idDonhang;
		
		private System.Nullable<int> _idKhachhang;
		
		private System.Nullable<System.DateTime> _ngayDathang;
		
		private System.Nullable<System.DateTime> _ngayGiaohang;
		
		private System.Nullable<bool> _Tinhtranggiaohang;
		
		private System.Nullable<bool> _Dathanhtoan;
		
		private EntitySet<Chitietdonhang> _Chitietdonhangs;
		
		private EntityRef<Khachhang> _Khachhang;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidDonhangChanging(int value);
    partial void OnidDonhangChanged();
    partial void OnidKhachhangChanging(System.Nullable<int> value);
    partial void OnidKhachhangChanged();
    partial void OnngayDathangChanging(System.Nullable<System.DateTime> value);
    partial void OnngayDathangChanged();
    partial void OnngayGiaohangChanging(System.Nullable<System.DateTime> value);
    partial void OnngayGiaohangChanged();
    partial void OnTinhtranggiaohangChanging(System.Nullable<bool> value);
    partial void OnTinhtranggiaohangChanged();
    partial void OnDathanhtoanChanging(System.Nullable<bool> value);
    partial void OnDathanhtoanChanged();
    #endregion
		
		public Donhang()
		{
			this._Chitietdonhangs = new EntitySet<Chitietdonhang>(new Action<Chitietdonhang>(this.attach_Chitietdonhangs), new Action<Chitietdonhang>(this.detach_Chitietdonhangs));
			this._Khachhang = default(EntityRef<Khachhang>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idDonhang", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int idDonhang
		{
			get
			{
				return this._idDonhang;
			}
			set
			{
				if ((this._idDonhang != value))
				{
					this.OnidDonhangChanging(value);
					this.SendPropertyChanging();
					this._idDonhang = value;
					this.SendPropertyChanged("idDonhang");
					this.OnidDonhangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idKhachhang", DbType="Int")]
		public System.Nullable<int> idKhachhang
		{
			get
			{
				return this._idKhachhang;
			}
			set
			{
				if ((this._idKhachhang != value))
				{
					if (this._Khachhang.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnidKhachhangChanging(value);
					this.SendPropertyChanging();
					this._idKhachhang = value;
					this.SendPropertyChanged("idKhachhang");
					this.OnidKhachhangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ngayDathang", DbType="DateTime")]
		public System.Nullable<System.DateTime> ngayDathang
		{
			get
			{
				return this._ngayDathang;
			}
			set
			{
				if ((this._ngayDathang != value))
				{
					this.OnngayDathangChanging(value);
					this.SendPropertyChanging();
					this._ngayDathang = value;
					this.SendPropertyChanged("ngayDathang");
					this.OnngayDathangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ngayGiaohang", DbType="DateTime")]
		public System.Nullable<System.DateTime> ngayGiaohang
		{
			get
			{
				return this._ngayGiaohang;
			}
			set
			{
				if ((this._ngayGiaohang != value))
				{
					this.OnngayGiaohangChanging(value);
					this.SendPropertyChanging();
					this._ngayGiaohang = value;
					this.SendPropertyChanged("ngayGiaohang");
					this.OnngayGiaohangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tinhtranggiaohang", DbType="Bit")]
		public System.Nullable<bool> Tinhtranggiaohang
		{
			get
			{
				return this._Tinhtranggiaohang;
			}
			set
			{
				if ((this._Tinhtranggiaohang != value))
				{
					this.OnTinhtranggiaohangChanging(value);
					this.SendPropertyChanging();
					this._Tinhtranggiaohang = value;
					this.SendPropertyChanged("Tinhtranggiaohang");
					this.OnTinhtranggiaohangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Dathanhtoan", DbType="Bit")]
		public System.Nullable<bool> Dathanhtoan
		{
			get
			{
				return this._Dathanhtoan;
			}
			set
			{
				if ((this._Dathanhtoan != value))
				{
					this.OnDathanhtoanChanging(value);
					this.SendPropertyChanging();
					this._Dathanhtoan = value;
					this.SendPropertyChanged("Dathanhtoan");
					this.OnDathanhtoanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Donhang_Chitietdonhang", Storage="_Chitietdonhangs", ThisKey="idDonhang", OtherKey="idDonhang")]
		public EntitySet<Chitietdonhang> Chitietdonhangs
		{
			get
			{
				return this._Chitietdonhangs;
			}
			set
			{
				this._Chitietdonhangs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Khachhang_Donhang", Storage="_Khachhang", ThisKey="idKhachhang", OtherKey="idKhachhang", IsForeignKey=true)]
		public Khachhang Khachhang
		{
			get
			{
				return this._Khachhang.Entity;
			}
			set
			{
				Khachhang previousValue = this._Khachhang.Entity;
				if (((previousValue != value) 
							|| (this._Khachhang.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Khachhang.Entity = null;
						previousValue.Donhangs.Remove(this);
					}
					this._Khachhang.Entity = value;
					if ((value != null))
					{
						value.Donhangs.Add(this);
						this._idKhachhang = value.idKhachhang;
					}
					else
					{
						this._idKhachhang = default(Nullable<int>);
					}
					this.SendPropertyChanged("Khachhang");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Chitietdonhangs(Chitietdonhang entity)
		{
			this.SendPropertyChanging();
			entity.Donhang = this;
		}
		
		private void detach_Chitietdonhangs(Chitietdonhang entity)
		{
			this.SendPropertyChanging();
			entity.Donhang = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Khachhang")]
	public partial class Khachhang : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _idKhachhang;
		
		private string _tenKhachhang;
		
		private string _sdtKhachhang;
		
		private string _diachiKhachhang;
		
		private System.Nullable<System.DateTime> _ngaysinhKhachhang;
		
		private string _taikhoanKhachhang;
		
		private string _matkhauKhachhang;
		
		private string _emailKhachhang;
		
		private EntitySet<Donhang> _Donhangs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidKhachhangChanging(int value);
    partial void OnidKhachhangChanged();
    partial void OntenKhachhangChanging(string value);
    partial void OntenKhachhangChanged();
    partial void OnsdtKhachhangChanging(string value);
    partial void OnsdtKhachhangChanged();
    partial void OndiachiKhachhangChanging(string value);
    partial void OndiachiKhachhangChanged();
    partial void OnngaysinhKhachhangChanging(System.Nullable<System.DateTime> value);
    partial void OnngaysinhKhachhangChanged();
    partial void OntaikhoanKhachhangChanging(string value);
    partial void OntaikhoanKhachhangChanged();
    partial void OnmatkhauKhachhangChanging(string value);
    partial void OnmatkhauKhachhangChanged();
    partial void OnemailKhachhangChanging(string value);
    partial void OnemailKhachhangChanged();
    #endregion
		
		public Khachhang()
		{
			this._Donhangs = new EntitySet<Donhang>(new Action<Donhang>(this.attach_Donhangs), new Action<Donhang>(this.detach_Donhangs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idKhachhang", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int idKhachhang
		{
			get
			{
				return this._idKhachhang;
			}
			set
			{
				if ((this._idKhachhang != value))
				{
					this.OnidKhachhangChanging(value);
					this.SendPropertyChanging();
					this._idKhachhang = value;
					this.SendPropertyChanged("idKhachhang");
					this.OnidKhachhangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tenKhachhang", DbType="NVarChar(500)")]
		public string tenKhachhang
		{
			get
			{
				return this._tenKhachhang;
			}
			set
			{
				if ((this._tenKhachhang != value))
				{
					this.OntenKhachhangChanging(value);
					this.SendPropertyChanging();
					this._tenKhachhang = value;
					this.SendPropertyChanged("tenKhachhang");
					this.OntenKhachhangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sdtKhachhang", DbType="VarChar(50)")]
		public string sdtKhachhang
		{
			get
			{
				return this._sdtKhachhang;
			}
			set
			{
				if ((this._sdtKhachhang != value))
				{
					this.OnsdtKhachhangChanging(value);
					this.SendPropertyChanging();
					this._sdtKhachhang = value;
					this.SendPropertyChanged("sdtKhachhang");
					this.OnsdtKhachhangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_diachiKhachhang", DbType="NVarChar(500)")]
		public string diachiKhachhang
		{
			get
			{
				return this._diachiKhachhang;
			}
			set
			{
				if ((this._diachiKhachhang != value))
				{
					this.OndiachiKhachhangChanging(value);
					this.SendPropertyChanging();
					this._diachiKhachhang = value;
					this.SendPropertyChanged("diachiKhachhang");
					this.OndiachiKhachhangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ngaysinhKhachhang", DbType="Date")]
		public System.Nullable<System.DateTime> ngaysinhKhachhang
		{
			get
			{
				return this._ngaysinhKhachhang;
			}
			set
			{
				if ((this._ngaysinhKhachhang != value))
				{
					this.OnngaysinhKhachhangChanging(value);
					this.SendPropertyChanging();
					this._ngaysinhKhachhang = value;
					this.SendPropertyChanged("ngaysinhKhachhang");
					this.OnngaysinhKhachhangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_taikhoanKhachhang", DbType="VarChar(50)")]
		public string taikhoanKhachhang
		{
			get
			{
				return this._taikhoanKhachhang;
			}
			set
			{
				if ((this._taikhoanKhachhang != value))
				{
					this.OntaikhoanKhachhangChanging(value);
					this.SendPropertyChanging();
					this._taikhoanKhachhang = value;
					this.SendPropertyChanged("taikhoanKhachhang");
					this.OntaikhoanKhachhangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_matkhauKhachhang", DbType="VarChar(50)")]
		public string matkhauKhachhang
		{
			get
			{
				return this._matkhauKhachhang;
			}
			set
			{
				if ((this._matkhauKhachhang != value))
				{
					this.OnmatkhauKhachhangChanging(value);
					this.SendPropertyChanging();
					this._matkhauKhachhang = value;
					this.SendPropertyChanged("matkhauKhachhang");
					this.OnmatkhauKhachhangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_emailKhachhang", DbType="VarChar(50)")]
		public string emailKhachhang
		{
			get
			{
				return this._emailKhachhang;
			}
			set
			{
				if ((this._emailKhachhang != value))
				{
					this.OnemailKhachhangChanging(value);
					this.SendPropertyChanging();
					this._emailKhachhang = value;
					this.SendPropertyChanged("emailKhachhang");
					this.OnemailKhachhangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Khachhang_Donhang", Storage="_Donhangs", ThisKey="idKhachhang", OtherKey="idKhachhang")]
		public EntitySet<Donhang> Donhangs
		{
			get
			{
				return this._Donhangs;
			}
			set
			{
				this._Donhangs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Donhangs(Donhang entity)
		{
			this.SendPropertyChanging();
			entity.Khachhang = this;
		}
		
		private void detach_Donhangs(Donhang entity)
		{
			this.SendPropertyChanging();
			entity.Khachhang = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Loaisanpham")]
	public partial class Loaisanpham : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _idLoaisanpham;
		
		private string _tenLoaisanpham;
		
		private EntitySet<Sanpham> _Sanphams;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidLoaisanphamChanging(int value);
    partial void OnidLoaisanphamChanged();
    partial void OntenLoaisanphamChanging(string value);
    partial void OntenLoaisanphamChanged();
    #endregion
		
		public Loaisanpham()
		{
			this._Sanphams = new EntitySet<Sanpham>(new Action<Sanpham>(this.attach_Sanphams), new Action<Sanpham>(this.detach_Sanphams));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idLoaisanpham", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int idLoaisanpham
		{
			get
			{
				return this._idLoaisanpham;
			}
			set
			{
				if ((this._idLoaisanpham != value))
				{
					this.OnidLoaisanphamChanging(value);
					this.SendPropertyChanging();
					this._idLoaisanpham = value;
					this.SendPropertyChanged("idLoaisanpham");
					this.OnidLoaisanphamChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tenLoaisanpham", DbType="NVarChar(500)")]
		public string tenLoaisanpham
		{
			get
			{
				return this._tenLoaisanpham;
			}
			set
			{
				if ((this._tenLoaisanpham != value))
				{
					this.OntenLoaisanphamChanging(value);
					this.SendPropertyChanging();
					this._tenLoaisanpham = value;
					this.SendPropertyChanged("tenLoaisanpham");
					this.OntenLoaisanphamChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Loaisanpham_Sanpham", Storage="_Sanphams", ThisKey="idLoaisanpham", OtherKey="idLoaisanpham")]
		public EntitySet<Sanpham> Sanphams
		{
			get
			{
				return this._Sanphams;
			}
			set
			{
				this._Sanphams.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Sanphams(Sanpham entity)
		{
			this.SendPropertyChanging();
			entity.Loaisanpham = this;
		}
		
		private void detach_Sanphams(Sanpham entity)
		{
			this.SendPropertyChanging();
			entity.Loaisanpham = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Nhanhieu")]
	public partial class Nhanhieu : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _idNhanhieu;
		
		private string _tenNhanhieu;
		
		private EntitySet<Sanpham> _Sanphams;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidNhanhieuChanging(int value);
    partial void OnidNhanhieuChanged();
    partial void OntenNhanhieuChanging(string value);
    partial void OntenNhanhieuChanged();
    #endregion
		
		public Nhanhieu()
		{
			this._Sanphams = new EntitySet<Sanpham>(new Action<Sanpham>(this.attach_Sanphams), new Action<Sanpham>(this.detach_Sanphams));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idNhanhieu", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int idNhanhieu
		{
			get
			{
				return this._idNhanhieu;
			}
			set
			{
				if ((this._idNhanhieu != value))
				{
					this.OnidNhanhieuChanging(value);
					this.SendPropertyChanging();
					this._idNhanhieu = value;
					this.SendPropertyChanged("idNhanhieu");
					this.OnidNhanhieuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tenNhanhieu", DbType="NVarChar(500)")]
		public string tenNhanhieu
		{
			get
			{
				return this._tenNhanhieu;
			}
			set
			{
				if ((this._tenNhanhieu != value))
				{
					this.OntenNhanhieuChanging(value);
					this.SendPropertyChanging();
					this._tenNhanhieu = value;
					this.SendPropertyChanged("tenNhanhieu");
					this.OntenNhanhieuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Nhanhieu_Sanpham", Storage="_Sanphams", ThisKey="idNhanhieu", OtherKey="idNhanhieu")]
		public EntitySet<Sanpham> Sanphams
		{
			get
			{
				return this._Sanphams;
			}
			set
			{
				this._Sanphams.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Sanphams(Sanpham entity)
		{
			this.SendPropertyChanging();
			entity.Nhanhieu = this;
		}
		
		private void detach_Sanphams(Sanpham entity)
		{
			this.SendPropertyChanging();
			entity.Nhanhieu = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Sanpham")]
	public partial class Sanpham : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _idSanpham;
		
		private string _tenSanpham;
		
		private string _motaSanpham;
		
		private System.Nullable<int> _idNhanhieu;
		
		private System.Nullable<int> _idLoaisanpham;
		
		private string _hinhSanpham;
		
		private System.Nullable<decimal> _giabanSanpham;
		
		private System.Nullable<int> _Soluongton;
		
		private System.Nullable<System.DateTime> _ngaycapnhat;
		
		private EntitySet<Chitietdonhang> _Chitietdonhangs;
		
		private EntityRef<Loaisanpham> _Loaisanpham;
		
		private EntityRef<Nhanhieu> _Nhanhieu;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidSanphamChanging(int value);
    partial void OnidSanphamChanged();
    partial void OntenSanphamChanging(string value);
    partial void OntenSanphamChanged();
    partial void OnmotaSanphamChanging(string value);
    partial void OnmotaSanphamChanged();
    partial void OnidNhanhieuChanging(System.Nullable<int> value);
    partial void OnidNhanhieuChanged();
    partial void OnidLoaisanphamChanging(System.Nullable<int> value);
    partial void OnidLoaisanphamChanged();
    partial void OnhinhSanphamChanging(string value);
    partial void OnhinhSanphamChanged();
    partial void OngiabanSanphamChanging(System.Nullable<decimal> value);
    partial void OngiabanSanphamChanged();
    partial void OnSoluongtonChanging(System.Nullable<int> value);
    partial void OnSoluongtonChanged();
    partial void OnngaycapnhatChanging(System.Nullable<System.DateTime> value);
    partial void OnngaycapnhatChanged();
    #endregion
		
		public Sanpham()
		{
			this._Chitietdonhangs = new EntitySet<Chitietdonhang>(new Action<Chitietdonhang>(this.attach_Chitietdonhangs), new Action<Chitietdonhang>(this.detach_Chitietdonhangs));
			this._Loaisanpham = default(EntityRef<Loaisanpham>);
			this._Nhanhieu = default(EntityRef<Nhanhieu>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idSanpham", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int idSanpham
		{
			get
			{
				return this._idSanpham;
			}
			set
			{
				if ((this._idSanpham != value))
				{
					this.OnidSanphamChanging(value);
					this.SendPropertyChanging();
					this._idSanpham = value;
					this.SendPropertyChanged("idSanpham");
					this.OnidSanphamChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tenSanpham", DbType="NVarChar(500) NOT NULL", CanBeNull=false)]
		public string tenSanpham
		{
			get
			{
				return this._tenSanpham;
			}
			set
			{
				if ((this._tenSanpham != value))
				{
					this.OntenSanphamChanging(value);
					this.SendPropertyChanging();
					this._tenSanpham = value;
					this.SendPropertyChanged("tenSanpham");
					this.OntenSanphamChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_motaSanpham", DbType="NVarChar(MAX)")]
		public string motaSanpham
		{
			get
			{
				return this._motaSanpham;
			}
			set
			{
				if ((this._motaSanpham != value))
				{
					this.OnmotaSanphamChanging(value);
					this.SendPropertyChanging();
					this._motaSanpham = value;
					this.SendPropertyChanged("motaSanpham");
					this.OnmotaSanphamChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idNhanhieu", DbType="Int")]
		public System.Nullable<int> idNhanhieu
		{
			get
			{
				return this._idNhanhieu;
			}
			set
			{
				if ((this._idNhanhieu != value))
				{
					if (this._Nhanhieu.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnidNhanhieuChanging(value);
					this.SendPropertyChanging();
					this._idNhanhieu = value;
					this.SendPropertyChanged("idNhanhieu");
					this.OnidNhanhieuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idLoaisanpham", DbType="Int")]
		public System.Nullable<int> idLoaisanpham
		{
			get
			{
				return this._idLoaisanpham;
			}
			set
			{
				if ((this._idLoaisanpham != value))
				{
					if (this._Loaisanpham.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnidLoaisanphamChanging(value);
					this.SendPropertyChanging();
					this._idLoaisanpham = value;
					this.SendPropertyChanged("idLoaisanpham");
					this.OnidLoaisanphamChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_hinhSanpham", DbType="VarChar(500)")]
		public string hinhSanpham
		{
			get
			{
				return this._hinhSanpham;
			}
			set
			{
				if ((this._hinhSanpham != value))
				{
					this.OnhinhSanphamChanging(value);
					this.SendPropertyChanging();
					this._hinhSanpham = value;
					this.SendPropertyChanged("hinhSanpham");
					this.OnhinhSanphamChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_giabanSanpham", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> giabanSanpham
		{
			get
			{
				return this._giabanSanpham;
			}
			set
			{
				if ((this._giabanSanpham != value))
				{
					this.OngiabanSanphamChanging(value);
					this.SendPropertyChanging();
					this._giabanSanpham = value;
					this.SendPropertyChanged("giabanSanpham");
					this.OngiabanSanphamChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Soluongton", DbType="Int")]
		public System.Nullable<int> Soluongton
		{
			get
			{
				return this._Soluongton;
			}
			set
			{
				if ((this._Soluongton != value))
				{
					this.OnSoluongtonChanging(value);
					this.SendPropertyChanging();
					this._Soluongton = value;
					this.SendPropertyChanged("Soluongton");
					this.OnSoluongtonChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ngaycapnhat", DbType="DateTime")]
		public System.Nullable<System.DateTime> ngaycapnhat
		{
			get
			{
				return this._ngaycapnhat;
			}
			set
			{
				if ((this._ngaycapnhat != value))
				{
					this.OnngaycapnhatChanging(value);
					this.SendPropertyChanging();
					this._ngaycapnhat = value;
					this.SendPropertyChanged("ngaycapnhat");
					this.OnngaycapnhatChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Sanpham_Chitietdonhang", Storage="_Chitietdonhangs", ThisKey="idSanpham", OtherKey="idSanpham")]
		public EntitySet<Chitietdonhang> Chitietdonhangs
		{
			get
			{
				return this._Chitietdonhangs;
			}
			set
			{
				this._Chitietdonhangs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Loaisanpham_Sanpham", Storage="_Loaisanpham", ThisKey="idLoaisanpham", OtherKey="idLoaisanpham", IsForeignKey=true)]
		public Loaisanpham Loaisanpham
		{
			get
			{
				return this._Loaisanpham.Entity;
			}
			set
			{
				Loaisanpham previousValue = this._Loaisanpham.Entity;
				if (((previousValue != value) 
							|| (this._Loaisanpham.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Loaisanpham.Entity = null;
						previousValue.Sanphams.Remove(this);
					}
					this._Loaisanpham.Entity = value;
					if ((value != null))
					{
						value.Sanphams.Add(this);
						this._idLoaisanpham = value.idLoaisanpham;
					}
					else
					{
						this._idLoaisanpham = default(Nullable<int>);
					}
					this.SendPropertyChanged("Loaisanpham");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Nhanhieu_Sanpham", Storage="_Nhanhieu", ThisKey="idNhanhieu", OtherKey="idNhanhieu", IsForeignKey=true)]
		public Nhanhieu Nhanhieu
		{
			get
			{
				return this._Nhanhieu.Entity;
			}
			set
			{
				Nhanhieu previousValue = this._Nhanhieu.Entity;
				if (((previousValue != value) 
							|| (this._Nhanhieu.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Nhanhieu.Entity = null;
						previousValue.Sanphams.Remove(this);
					}
					this._Nhanhieu.Entity = value;
					if ((value != null))
					{
						value.Sanphams.Add(this);
						this._idNhanhieu = value.idNhanhieu;
					}
					else
					{
						this._idNhanhieu = default(Nullable<int>);
					}
					this.SendPropertyChanged("Nhanhieu");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Chitietdonhangs(Chitietdonhang entity)
		{
			this.SendPropertyChanging();
			entity.Sanpham = this;
		}
		
		private void detach_Chitietdonhangs(Chitietdonhang entity)
		{
			this.SendPropertyChanging();
			entity.Sanpham = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Admin")]
	public partial class Admin : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _UserAdmin;
		
		private string _PasswordAdmin;
		
		private string _Hoten;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnUserAdminChanging(string value);
    partial void OnUserAdminChanged();
    partial void OnPasswordAdminChanging(string value);
    partial void OnPasswordAdminChanged();
    partial void OnHotenChanging(string value);
    partial void OnHotenChanged();
    #endregion
		
		public Admin()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserAdmin", DbType="VarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string UserAdmin
		{
			get
			{
				return this._UserAdmin;
			}
			set
			{
				if ((this._UserAdmin != value))
				{
					this.OnUserAdminChanging(value);
					this.SendPropertyChanging();
					this._UserAdmin = value;
					this.SendPropertyChanged("UserAdmin");
					this.OnUserAdminChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PasswordAdmin", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string PasswordAdmin
		{
			get
			{
				return this._PasswordAdmin;
			}
			set
			{
				if ((this._PasswordAdmin != value))
				{
					this.OnPasswordAdminChanging(value);
					this.SendPropertyChanging();
					this._PasswordAdmin = value;
					this.SendPropertyChanged("PasswordAdmin");
					this.OnPasswordAdminChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Hoten", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string Hoten
		{
			get
			{
				return this._Hoten;
			}
			set
			{
				if ((this._Hoten != value))
				{
					this.OnHotenChanging(value);
					this.SendPropertyChanging();
					this._Hoten = value;
					this.SendPropertyChanged("Hoten");
					this.OnHotenChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
